[project]
name = "proj-01-python-taximeter-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "kivy>=2.3.1",
    "numpy>=2.2.2",
    "pysimplegui>=5.0.8",
]
